blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
# from django.utils.translation import gettext_lazy as _


urlpatterns = [
    # django rest api
    path("api-auth/", include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("", include("jobs.urls", namespace="jobs")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_url = None
admin.site.site_header = "HuminImp Administration"

jobs/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from . import views
from . import api

app_name = "jobs"

urlpatterns = [
    path("", views.index, name="index"),
    path("reply/", views.reply, name="reply"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("blogs_filter/", views.blogs_filter, name="blogs_filter"),

    path("blogs/", views.blogs_list, name="blogs"),
    path("blogs/<int:id>", views.blog_detail, name="blog_detail"),
    # api
    path("api/blogs", api.blogs_api, name="blogs_api"),
    path("api/blogs/<int:id>", api.detail_api, name="detail_api"),
    # class based views
    path(
        "api/v2/blogs",
        api.BlogListApi.as_view(),
        name="BlogListApi",
    ),
    path(
        "api/v2/blogs/<int:id>",
        api.BlogDetail.as_view(),
        name="BlogDetail",
    ),
]

jobs/models.py
from django.db import models
from .validators import validate_file_extension, validate_image_extension
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from datetime import date
from django.core.validators import MinValueValidator

from  embed_video.fields  import  EmbedVideoField


class Replay(models.Model):
    image_bg_volunteer = models.FileField(
        validators=[validate_image_extension],
        upload_to="background/volunteer/",
    )


class About(models.Model):
    image_middle_about = models.FileField(
        validators=[validate_image_extension],
        upload_to="background/about/",
        blank=True,
        null=True,
    )
    



class Category(models.Model):
    ar_name = models.CharField(blank=False, null=False, max_length=100)
    en_name = models.CharField(blank=False, null=False, max_length=100)
    
    def __str__(self):
        return self.en_name


class Blog(models.Model):
    image_one = models.FileField(
        validators=[validate_image_extension],
        default="",
        upload_to="blogs/backgrounds/",
        blank=True,
    )

    date = models.DateField(default=date.today, blank=True)

    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    tutorial_Video = EmbedVideoField(blank=True, default="",)

    title = models.CharField(max_length=300, default="", blank=True)
    title_ar = models.CharField(max_length=300, default="", blank=True)
    authors = models.CharField(max_length=300, default="", blank=True)

    authors_ar = models.CharField(max_length=300, default="", blank=True)

    desc1 = models.CharField(max_length=200, default="", blank=True)
    desc1_ar = models.CharField(max_length=200, default="", blank=True)
    desc2 = models.TextField(max_length=40000, default="", blank=True)
    desc2_ar = models.TextField(max_length=40000, default="", blank=True)
    blank = models.CharField(max_length=600, default="", blank=True)
    blank_ar = models.CharField(max_length=600, default="", blank=True)
    desc3 = models.TextField(max_length=40000, default="", blank=True)
    desc3_ar = models.TextField(max_length=40000, default="", blank=True)
    desc4 = models.TextField(max_length=40000, default="", blank=True)
    desc4_ar = models.TextField(max_length=40000, default="", blank=True)
    desc5 = models.TextField(max_length=40000, default="", blank=True)
    desc5_ar = models.TextField(max_length=40000, default="", blank=True)
    desc6 = models.TextField(max_length=40000, default="", blank=True)
    desc6_ar = models.TextField(max_length=40000, default="", blank=True)
    subtitle = models.CharField(max_length=300, default="", blank=True)
    subtitle_ar = models.CharField(max_length=300, default="", blank=True)
    subtitle_desc1 = models.TextField(max_length=40000, default="", blank=True)
    subtitle_desc1_ar = models.TextField(
        max_length=4000, default="", blank=True
    )
    subtitle_desc2 = models.TextField(max_length=40000, default="", blank=True)
    subtitle_desc2_ar = models.TextField(
        max_length=40000, default="", blank=True
    )

    subtitle2 = models.CharField(max_length=300, default="", blank=True)
    subtitle2_ar = models.CharField(max_length=300, default="", blank=True)
    subtitle2_desc1 = models.TextField(max_length=40000, default="", blank=True)
    subtitle2_desc1_ar = models.TextField(
        max_length=40000, default="", blank=True
    )
    subtitle2_desc2 = models.TextField(max_length=40000, default="", blank=True)
    subtitle2_desc2_ar = models.TextField(
        max_length=40000, default="", blank=True
    )
    subtitle2_desc3 = models.TextField(max_length=40000, default="", blank=True)
    subtitle2_desc3_ar = models.TextField(
        max_length=40000, default="", blank=True
    )

    subtitle3 = models.CharField(max_length=300, default="", blank=True)
    subtitle3_ar = models.CharField(max_length=300, default="", blank=True)
    subtitle3_desc1 = models.TextField(max_length=40000, default="", blank=True)
    subtitle3_desc1_ar = models.TextField(
        max_length=40000, default="", blank=True
    )
    subtitle4 = models.CharField(max_length=300, default="", blank=True)
    subtitle4_ar = models.CharField(
        max_length=300, default="", blank=True
    )
    subtitle4_desc1 = models.TextField(max_length=40000, default="", blank=True)
    subtitle4_desc1_ar = models.TextField(
        max_length=40000, default="", blank=True
    )
    subtitle4_desc2 = models.TextField(max_length=40000, default="", blank=True)
    subtitle4_desc2_ar = models.TextField(
        max_length=40000, default="", blank=True
    )
  
    views = models.PositiveIntegerField(default=0, validators=[
            MinValueValidator(0)
    ])
    class Meta:
        ordering = ["-date"]




class Index(models.Model):
    text_about_index = models.TextField(
        max_length=1000,
        default="",
        blank=True,
    )
    text_about_index_ar = models.TextField(
        max_length=1000,
        default="",
        blank=True,
    )
    text_index = models.TextField(
        max_length=1000,
        default="",
        blank=True,
    )
    text_index_ar = models.TextField(
        max_length=1000,
        default="",
        blank=True,
    )
    
    

jobs/views.py
from django.db.models import F
from email.message import EmailMessage
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.core.paginator import Paginator
from rest_framework import generics, permissions
from .models import Replay, Blog, Index, About 
from .serializers import (
    ReplaySerializer,
    CategorySerializer,
    IndexSerializer,
    
    AboutSerializer,
)
from django.http import HttpRequest
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from .filters import BlogFilter
from django.core.paginator import Paginator
from django.utils.translation import get_language, activate

from django.core.mail import send_mail, EmailMessage


def reply(request):
    """Renders the create replay page."""
    assert isinstance(request, HttpRequest)
    queryset = Replay.objects.all()
    serializer_class = ReplaySerializer(queryset, many=True)

    return render(
        request,
        "reply.html",
        {
            "data": serializer_class.data,
        },
    )


def index(request):
    assert isinstance(request, HttpRequest)
    queryset = Index.objects.all()
    serializer_class = IndexSerializer(queryset, many=True)

    blogs = Blog.objects.all()

    # Show many contacts per page for stories
    paginator_story = Paginator(blogs, 10000000000000000)
    page_number_story = request.GET.get("page")
    page_obj_story = paginator_story.get_page(page_number_story)

    context = {
        "data": serializer_class.data,
        "blog": page_obj_story,
    }
    return render(request, "index.html", context)


def contact(request):
    about_image_bg = About.objects.all()

    if request.method == "POST":
        name = request.POST.get("full_name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        subject = request.POST.get("subject")
        data = {
            "name": name,
            "email": email,
      "subject": subject,

            "message": message,
        }
        print(data)

        message = '''
        Subject :{}
        New message :{}
        email :{}
        From: {}
        '''.format(
            data["subject"], data["message"], data["email"], data["name"]
        )

        if name and message and email and subject:
            try:
                send_mail(
                    data["name"],
                    message,
                    from_email="tabtickb@gmail.com",
                    recipient_list=["tabtickb@gmail.com"],
                    fail_silently=False,
                )

            except Exception as error:
                print("error")
                print(error)
                return HttpResponse("Invalid header found.")
    return render(
        request,
        "contact.html",
        {
            "about_image_bg": about_image_bg,
        },
    )


def translate(language):
    cur_language = get_language()
    try:
        activate(language)
    finally:
        activate(cur_language)


def about(request):
    """Renders the create about page."""
    assert isinstance(request, HttpRequest)
    queryset = About.objects.all()
    serializer_class = AboutSerializer(queryset, many=True)

    return render(
        request,
        "about.html",
        {"data": serializer_class.data, },
    )

def blogs_filter(request):

    order = request.GET.get("order", None)
    if order == "popularity":
        blogs = Blog.objects.order_by("-views")
    elif order == "latest":
        blogs = Blog.objects.all().order_by("-date")
    else:
        blogs = Blog.objects.all()
        
    blogs = BlogFilter(request.GET, queryset=blogs).qs
  
    # Show many contacts per page.
    # paginator = Paginator(blogs, 1)
    # page_number = request.GET.get("page")
    # blogs = paginator.get_page(page_number)

    if blogs:
        context = {
            "blogs": blogs,
        }  # template name

    else:
        context = {"message": "There are no blogs available at the moment."}
    return render(request, "blogs_filter.html", context)

def blogs_list(request):

    blogs = Blog.objects.all().order_by("-date")
    myfilter = BlogFilter(request.GET, queryset=blogs)
    blogs = myfilter.qs

    # Show many contacts per page.
    paginator = Paginator(blogs, 100000000000000000000)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    print(page_obj)
    print("hello")

    if blogs:
        context = {
            "blogs": page_obj,
            "myfilter": myfilter,
        }  # template name

    else:
        context = {"message": "There are no stories available at the moment."}
    return render(request, "blogs.html", context)


def blog_detail(request, id):

    blog = Blog.objects.filter(id=id).last()
    blog.views = F("views") + 1
    blog.save()
    blog.refresh_from_db()
    context = {"blog": blog,  'num_visits': blog.views}
    return render(request, "blog_detail.html", context)




def clear(request):
    return HttpResponse("")

jobs/templates/blogs.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}


<!-- Page Title Section Start -->
<div class="page-title-section section">
  <!-- <div class="page-title">
          <div class="container">
              <h1 class="title">Blog Masonry</h1>
          </div>
      </div> -->
  <div class="page-breadcrumb">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'jobs:index' %}">{% trans "Home" %}</a></li>
        <li class="current">{% trans "Blogs" %}</li>
      </ul>
    </div>
  </div>
</div>
<!-- Page Title Section End -->

<!-- Blog Section Start -->
<div class="section section-padding-bottom">
  <div class="container">
    <div class="row justify-content-between align-items-center max-mb-20">
      <div class="col-sm-auto col-12 max-mb-10">
        <p class="result-count">{% trans "We found" %} <span>{{blogs|length}}</span> {% trans "blogs available for you" %}</p>
      </div>
      
      <div class="col-sm-auto col-12 max-mb-10">
        <div class="col-sm-auto col-12 max-mb-10">
          <div class="col-sm-auto col-12 max-mb-10">
              {% if LANGUAGE_CODE == 'en' %}
          <select class="sort-by" onchange="location = this.value;">
            {% elif LANGUAGE_CODE == 'ar' %} 
            <select class="sort-by-arabic" onchange="location = this.value;">
              {% endif %}  
                       <option value="{% url 'jobs:blogs_filter' %}">{% trans "Default" %}</option>
              <option value="{% url 'jobs:blogs_filter' %}?order=popularity">{% trans "Popularity" %}</option>
              <option  value="{% url 'jobs:blogs_filter' %}?order=latest">{% trans "Latest" %}</option>
              <optgroup label="__">
                {% for category in categories  %}
              <option value="{% url 'jobs:blogs_filter' %}?category={{category}}">
                {% if LANGUAGE_CODE == 'en' %}
                  {{ category.en_name }}
                {% elif LANGUAGE_CODE == 'ar' %} 
                  {{ category.ar_name }}
                {% endif %}
              </option></a>
              {% endfor %}
            </optgroup>
  
              
            </select>
          </div>
         
          
        </div>

        
      </div>
    </div>
    <!-- Blog Wrapper Start -->
    <div class="blog-section section section-padding">
      <div class="container">

     
        <!-- Blog Wrapper Start -->
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 max-mb-n30">

            {% for blog in blogs %}  
            <!-- Blog Start -->
            <div class="grid-item col max-mb-30" data-aos="fade-up">
                <div class="blog-2">
                  <div class="thumbnail">
                    <a href="{{blog.image_one.url}}" class="image"><img src="{{blog.image_one.url}}" width="500" height="200"
                        alt="Blog Image"></a>
                  </div>
                  <div class="info">
                    <a href="" class="category">         {% if LANGUAGE_CODE == 'en' %}{{ blog.category.en_name }}
                      {% elif LANGUAGE_CODE == 'ar' %} {{ blog.category.ar_name }}{% endif %}</a>
                    <h3 class="title"><a href="{% url 'jobs:blog_detail' blog.id %}">{% if LANGUAGE_CODE == 'en' %}{{ blog.title }}
                      {% elif LANGUAGE_CODE == 'ar' %} {{ blog.title_ar }}{% endif %}</a></h3>
                    <div class="desc">
                      <p>        {% if LANGUAGE_CODE == 'en' %}{{ blog.desc1 }}
                        {% elif LANGUAGE_CODE == 'ar' %} {{ blog.desc1_ar }}{% endif %}</p>
                    </div>
                    <ul class="meta">
                      <li><i class="far fa-calendar"></i>  {{blog.date|date:'d M o'}}  </li>
                      <li><i class="far fa-user"></i>     {% if LANGUAGE_CODE == 'en' %}{{ blog.authors }}
                        {% elif LANGUAGE_CODE == 'ar' %} {{ blog.authors_ar }}{% endif %}   </li>
                    </ul>
                    <!-- Teacher Quote Wrapper Start -->
                    <div class="" data-aos="fade-up">
                      <!-- Teacher Quote Start -->
                    
        
                          <div class="experience" style="padding-top: 20px">
                            <a href="{% url 'jobs:blog_detail' blog.id %}" class="link">{% trans "Read more" %} <i
                                class="far fa-long-arrow-right"></i></a>
                         
                      </div>
                      <!-- Teacher Quote End -->
                    </div>
                    <!-- Teacher Quote Wrapper End -->
        
        
                  </div>
                </div>
              </div>
            <!-- Blog End -->
          {% endfor %}
        </div>
        <!-- Blog Wrapper End -->



       
    </div>
    </div>
    <!-- Blog End -->

  </div>

   

</div>

  {% endblock body %}

  

jobs/templates/blogs_filter.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}


<!-- Page Title Section Start -->
<div class="page-title-section section">
  <!-- <div class="page-title">
          <div class="container">
              <h1 class="title">Blog Masonry</h1>
          </div>
      </div> -->
  <div class="page-breadcrumb">
    <div class="container">
      <ul class="breadcrumb">
        <li><a href="{% url 'jobs:index' %}">{% trans "Home" %}</a></li>
        <li class="current"> <a href="{% url 'jobs:blogs' %}"> {% trans "Blogs" %}</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- Page Title Section End -->

<!-- Blog Section Start -->
<div class="section section-padding-bottom">
  <div class="container">
    <div class="row justify-content-between align-items-center max-mb-20">
      <div class="col-sm-auto col-12 max-mb-10">
        <p class="result-count">{% trans "We found" %} <span>{{blogs|length}}</span> {% trans "blogs available for you" %}</p>
      </div>
      
      <div class="col-sm-auto col-12 max-mb-10">
        <div class="col-sm-auto col-12 max-mb-10">
          {% if LANGUAGE_CODE == 'en' %}
          <select class="sort-by" onchange="location = this.value;">
            {% elif LANGUAGE_CODE == 'ar' %} 
            <select class="sort-by-arabic" onchange="location = this.value;">
              {% endif %}
            <option value="{% url 'jobs:blogs_filter' %}">{% trans "Default" %}</option>
            <option value="{% url 'jobs:blogs_filter' %}?order=popularity">{% trans "Popularity" %}</option>
            <option  value="{% url 'jobs:blogs_filter' %}?order=latest">{% trans "Latest" %}</option>
            <optgroup label="__">
              {% for category in categories  %}
            <option value="{% url 'jobs:blogs_filter' %}?category={{category}}">
              {% if LANGUAGE_CODE == 'en' %}
                {{ category.en_name }}
              {% elif LANGUAGE_CODE == 'ar' %} 
                {{ category.ar_name }}
              {% endif %}
            </option></a>
            {% endfor %}
          </optgroup>

            
          </select>
        </div>

        
      </div>
    </div>
  
        <!-- Blog Wrapper Start -->
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 max-mb-n30">

          {% for blog in blogs %}  
          <!-- Blog Start -->
          <div class="grid-item col max-mb-30" data-aos="fade-up">
              <div class="blog-2">
                <div class="thumbnail">
                  <a href="{{blog.image_one.url}}" class="image"><img src="{{blog.image_one.url}}" width="500" height="200"
                      alt="Blog Image"></a>
                </div>
                <div class="info">
                  <a href="" class="category">         {% if LANGUAGE_CODE == 'en' %}{{ blog.category.en_name }}
                    {% elif LANGUAGE_CODE == 'ar' %} {{ blog.category.ar_name }}{% endif %}</a>
                  <h3 class="title"><a href="{% url 'jobs:blog_detail' blog.id %}">{% if LANGUAGE_CODE == 'en' %}{{ blog.title }}
                    {% elif LANGUAGE_CODE == 'ar' %} {{ blog.title_ar }}{% endif %}</a></h3>
                  <div class="desc">
                    <p>        {% if LANGUAGE_CODE == 'en' %}{{ blog.desc1 }}
                      {% elif LANGUAGE_CODE == 'ar' %} {{ blog.desc1_ar }}{% endif %}</p>
                  </div>
                  <ul class="meta">
                    <li><i class="far fa-calendar"></i>  {{blog.date|date:'d M o'}}   </li>
                    <li><i class="far fa-user"></i>     {% if LANGUAGE_CODE == 'en' %}{{ blog.authors }}
                      {% elif LANGUAGE_CODE == 'ar' %} {{ blog.authors_ar }}{% endif %}   </li>
                  </ul>
                  <!-- Teacher Quote Wrapper Start -->
                  <div class="" data-aos="fade-up">
                    <!-- Teacher Quote Start -->
                  
      
                        <div class="experience" style="padding-top: 20px">
                          <a href="{% url 'jobs:blog_detail' blog.id %}" class="link">{% trans "Read more" %} <i
                              class="far fa-long-arrow-right"></i></a>
                       
                    </div>
                    <!-- Teacher Quote End -->
                  </div>
                  <!-- Teacher Quote Wrapper End -->
      
      
                </div>
              </div>
            </div>
          <!-- Blog End -->
        {% endfor %}
      </div>
      <!-- Blog Wrapper End -->

  </div>
  <!-- Blog Wrapper End -->

  <!-- Pagination Start -->
 
    

  <!-- Pagination End -->

</div>

</div>

  {% endblock body %}

jobs/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

        <!-- Slider/Intro Section Start -->
        <div class="intro4-section section section-fluid" data-bg-image="{% static 'careers/images/about/image_index.jpeg' %}">

            <div class="container">
                <div class="row">

                    <!-- Intro One Content Start -->
                    <div class="col-12" data-aos="fade-up">
                        <div class="intro4-content headline-active text-center">
                            <h1 class="title ah-headline">{% trans "Expand Your Knowledge" %}
                                
                            </h1>
                            <p> {% for i in data %}{% if LANGUAGE_CODE == 'en' %}{{i.text_index}}
                              {% elif LANGUAGE_CODE == 'ar' %}{{i.text_index_ar}}{% endif %} </p>
                
                            {% endfor %}</p>
                            <!-- <a href="{% url 'jobs:blogs' %}" class="btn btn-light btn-hover-primary"> {% trans "View all blogs" %} </a> -->
                            
                        </div>
                    </div>
                    <!-- Intro One Content End -->

                </div>
            </div>

            <!-- Section Bottom Shape Start -->
          
            <!-- Section Bottom Shape End -->

        </div>
     
    
 
<!-- Feature Section Start -->
<div class="section section-padding">
    <div class="container">

        <!-- Section Title Start -->
        <div class="section-title-two text-center" data-aos="fade-up">
            <span class="sub-title">{% trans "Let’s Know about TabTick"%}</span>
            <h2 class="title">{% for i in data %}
              <p> {% if LANGUAGE_CODE == 'en' %}{{i.text_about_index}}
                {% elif LANGUAGE_CODE == 'ar' %}{{i.text_about_index_ar}}{% endif %} </p>
  
              {% endfor %}</h2>
        </div>
        <!-- Section Title End -->

       

    </div>
</div>
<!-- Feature Section End -->

       
        <!-- Blog Section Start -->
        <div class="blog-section section section-padding" data-bg-color="#f8f8f8">
            <div class="container">

                <!-- Section Title Start -->
                <div class="section-title text-center" data-aos="fade-up">
                    <span class="sub-title">{% trans "Articles & Tips" %}</span>
                    <h2 class="title playfair-font">{% trans "Latest from" %} <span>{% trans "the blog" %}</span></h2>
                </div>
                <!-- Section Title End -->

                <!-- Blog Wrapper Start -->
                <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 max-mb-n30">

                    {% for blog in blog %}  {% if forloop.counter < 4 %}
                    <!-- Blog Start -->
                    <div class="grid-item col max-mb-30" data-aos="fade-up">
                        <div class="blog-2">
                          <div class="thumbnail">
                            <a href="{{blog.image_one.url}}" class="image"><img src="{{blog.image_one.url}}" width="500" height="200"
                                alt="Blog Image"></a>
                          </div>
                          <div class="info">
                            <a href="" class="category">         {% if LANGUAGE_CODE == 'en' %}{{ blog.category.en_name }}
                              {% elif LANGUAGE_CODE == 'ar' %} {{ blog.category.ar_name }}{% endif %}</a>
                            <h3 class="title"><a href="{% url 'jobs:blog_detail' blog.id %}">{% if LANGUAGE_CODE == 'en' %}{{ blog.title }}
                              {% elif LANGUAGE_CODE == 'ar' %} {{ blog.title_ar }}{% endif %}</a></h3>
                            <div class="desc">
                              <p>        {% if LANGUAGE_CODE == 'en' %}{{ blog.desc1 }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ blog.desc1_ar }}{% endif %}</p>
                            </div>
                            <ul class="meta">
                              <li><i class="far fa-calendar"></i>  {{blog.date|date:'d M o'}}    </li>
                              <li><i class="far fa-user"></i>     {% if LANGUAGE_CODE == 'en' %}{{ blog.authors }}
                                {% elif LANGUAGE_CODE == 'ar' %} {{ blog.authors_ar }}{% endif %}   </li>
                            </ul>
                            <!-- Teacher Quote Wrapper Start -->
                            <div class="" data-aos="fade-up">
                              <!-- Teacher Quote Start -->
                            
                
                                  <div class="experience" style="padding-top: 20px">
                                    <a href="{% url 'jobs:blog_detail' blog.id %}" class="link">{% trans "Read more" %} <i
                                        class="far fa-long-arrow-right"></i></a>
                                 
                              </div>
                              <!-- Teacher Quote End -->
                            </div>
                            <!-- Teacher Quote Wrapper End -->
                
                
                          </div>
                        </div>
                      </div>
                    <!-- Blog End -->
                    {% endif %} {% endfor %}
                </div>
                <!-- Blog Wrapper End -->



                <div class="row max-mt-70">
                    <div class="text-center col-lg-7 mx-auto">
                        <a class="link link-lg link-color" href="{% url 'jobs:blogs' %}">{% trans "Wanna transform your life?" %}​ <mark>{% trans "View all blogs" %} <i class="far fa-long-arrow-right"></i></mark></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Blog Section End -->

        {% endblock body %}

jobs/templates/reply.html
{% extends 'base2.html' %}
{% block body %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!-- End Main Header -->




  <!--Featured Blocks-->
  <div class="featured-blocks vission_mission_section">
    <div class="row clearfix">
    
      <!--Featured Block-->
      <div class="featured-block col-lg-12 col-md-12 col-sm-12">
        <div class="inner-box">
          <div class="iconss">
            <h3 style="text-align: center; padding-top: 50px;" class="replay-text-arabic"> {% trans "Thank You!" %}</h3>
            <div style="text-align: center;" class="icon">
              <span  class="flaticon-email-1"></span>
            </div>
          
            <div style="text-align: center;" class="replay-text-arabic-para">
              {% trans "For choosing Ashor Iraqi Foundation For Relief And Development, We’ll get back to you about your order as soon as possible." %}
              <p style="text-align: center; ">
                {% trans "Having trouble?" %} <a href="{% url 'jobs:contact' %}">{% trans "Contact us" %}</a>
              </p>
            </div>
            <div class="donate-link" style="text-align: center; padding-top: 30px;">
                <a href="{% url 'jobs:index' %}" class="theme-btn btn-style-one"
                ><span class="btn-title">{% trans "back to home page" %}</span></a
              >
           
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</div>
</section>

{% endblock body %}




   